### ISSUE TITLE
Throwing Undefined control sequence error for any section

### ISSUE THREAD

**Issue by teckcode** [vtex-soft/texsupport.iospress-jcs#1]
I tried to use the template-iopress-jcs and it gave me an error for each section I define. In the class file the section format is not defined.
```
\AtBeginDocument{%
  \global\let\ios@Sectionformat\Sectionformat
  \global\let\ios@startsection\@startsection
  \def\@startsection#1#2#3#4#5#6{%
    \xdef\ios@section@namelevel{#1}%
    \xdef\ios@section@numlevel{#2}%
    \ios@startsection{#1}{#2}{#3}{#4}{#5}{#6}%
    }%
  \gdef\Sectionformat#1#2{%
    \ios@Sectionformat{#1\@nameuse{ios@section@level@\ios@section@numlevel @sep}}{#2}%
    }%
  \let\ios@NR@ssect\NR@ssect
  \def\NR@ssect#1#2#3#4#5{%
    \stepcounter{ios@section@star}%
    \def\ios@section@star@id{\ios@section@namelevel *.\the\c@ios@section@star}%
    \pdfbookmark[\ios@section@numlevel]{#5}\ios@section@star@id
    \ios@NR@ssect{#1}{#2}{#3}{#4}{#5}%
    }%
  }
```
I tried to use `\AtBeginDocument{\let\ios@Sectionformat\relax}` to avoid the error , I got other errors related to bibliography items included. However, I'm using a saparete file for bibliography(.bib file). 
`Missing number, treated as zero. \begin{thebibliography}{18} `  

some suggest to use \usepackage{hyperref}, it didn't work. You quick response is highly appreciated.

**Comment by monga** [comment]
The authors seem not very reactive... I found the same issue in another project of the same organization: https://github.com/vtex-soft/texsupport.mii-infor/issues/1

My workaround is here: https://github.com/vtex-soft/texsupport.mii-infor/pull/2

**Comment by mingiss** [comment]
Sorry for late response. Notifications need some fixing. 
The error is related to changes of {hyperref} in tl2020. Another workaround could be used too: 
\usepackage{nameref} 
Corrected document class will be ready soon.

**Comment by mingiss** [comment]
The class file updated:
https://github.com/vtex-soft/texsupport.iospress-jcs/blob/master/iosart2x.cls
